name: extension
description: Package including lot helpers for easy developing on dart language
version: 0.6.1
homepage: https://github.com/ScerIO/packages.dart/tree/master/packages/extension

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: 1.15.0

dev_dependencies:
  test: 1.24.0
