name: universal_file
description: Cross-platform File & Directory that works in all platforms (browsers, Flutter, and VM)
repository: https://github.com/rbcprolabs/packages.dart/tree/master/packages/universal_file
issue_tracker: https://github.com/rbcprolabs/packages.dart/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+universal_file%22
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: 1.15.0

dev_dependencies:
  test: 1.24.0
  lints: 4.0.0